name = "displayce-dashboard"
main = "src/index.js"
compatibility_date = "2024-09-23"

[assets]
directory = "./public"
binding = "ASSETS"

# Configuração do Banco de Dados D1
[[d1_databases]]
binding = "DB" 
database_name = "displayce-db"
database_id = "b7b497f1-6da9-4607-9957-9e960ef0927b" 

# Agendamento do Cron
[triggers]
crons = ["0 * * * *"] 

[vars]
API_BASE_URL = "https://datahub.displayce.com/agencies/v2/rtb"
