name = "dash0pdooh"
main = "worker/index.js"
compatibility_date = "2024-01-01"

# Configuração do Site Estático (Frontend)
[site]
bucket = "./public"
# Configuração do Banco de Dados D1
[[d1_databases]]
binding = "DB" # Nome da variável no código do Worker
database_name = "displayce-db"
database_id = "b7b497f1-6da9-4607-9957-9e960ef0927b" # Será preenchido após criar no Cloudflare

# Agendamento do Robô (Cron Trigger)
[triggers]
crons = ["0 * * * *"] # Roda a cada hora (minuto 0)

# Variáveis de Ambiente (Segredos não vão aqui, via comando)
[vars]
API_BASE_URL = "https://datahub.displayce.com/agencies/v2/rtb"
